version: "3.6"

services:
  app:
    build: .
    container_name: app
    env_file:
      - .env
    command: bash -c "python manage.py migrate && python manage.py initadmin && python manage.py runserver"
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    volumes:
      - .:/code
    restart: always

  postgres:
    image: postgres:12
    container_name: postgres
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: {}