version: "3.6"

services:
  app:
    build: .
    container_name: app
    env_file:
      - .env
    command: bash -c "python manage.py migrate &&
                      python manage.py initadmin &&
                      python manage.py collectstatic --noinput &&
                      uwsgi --ini uwsgi.ini"
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - redis
    volumes:
      - .:/code
    restart: always

  celery:
    build: .
    container_name: celery
    env_file:
      - .env
    command: celery -A manager_tasks.celery_blog worker -l info
    volumes:
      - .:/code
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres:12
    container_name: postgres
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

  redis:
    image: redis:latest
    container_name: redis
    ports:
        - "6379:6379"
    restart: always

volumes:
  pgdata: {}