# Generated by Django 3.0.4 on 2020-03-20 11:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('timeline', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Блог',
                'verbose_name_plural': 'Блоги',
            },
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Заголовок')),
                ('text', models.TextField(verbose_name='Текст')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Blog', verbose_name='Блог')),
            ],
            options={
                'verbose_name': 'Запись',
                'verbose_name_plural': 'Записи',
            },
        ),
        migrations.CreateModel(
            name='SubscribeRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_read', models.BooleanField(verbose_name='Запись прочитана пользователем')),
                ('record', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='blog.Record', verbose_name='Запись')),
            ],
            options={
                'verbose_name': 'Запись из блога на которую подписан пользователь',
                'verbose_name_plural': 'Записи из блога на которую подписан пользователь',
            },
        ),
        migrations.CreateModel(
            name='SubscribeByBlog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('subscribes_by_blog', models.ManyToManyField(to='blog.SubscribeRecord', verbose_name='Подписка на новость')),
                ('timeline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timeline.Timeline', verbose_name='Лента записей')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Подписка на блог',
                'verbose_name_plural': 'Подписки на блоги',
            },
        ),
        migrations.AddField(
            model_name='blog',
            name='subscribes_by_blog',
            field=models.ManyToManyField(to='blog.SubscribeByBlog', verbose_name='Подписки на блог'),
        ),
        migrations.AddField(
            model_name='blog',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
