# Generated by Django 3.0.4 on 2020-03-20 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscribebyblog',
            old_name='subscribes_by_blog',
            new_name='subscribes_record',
        ),
    ]
