# Generated by Django 3.0.4 on 2020-03-21 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200320_1150'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscribebyblog',
            name='user',
        ),
        migrations.AlterField(
            model_name='subscriberecord',
            name='is_read',
            field=models.BooleanField(default=False, verbose_name='Запись прочитана пользователем'),
        ),
    ]
