# Generated by Django 3.0.4 on 2020-03-20 06:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0003_auto_20200319_1443'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscribeByBlog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Подписка на блог',
                'verbose_name_plural': 'Подписки на блоги',
            },
        ),
        migrations.AddField(
            model_name='blog',
            name='subscribes_by_blog',
            field=models.ManyToManyField(to='blog.SubscribeByBlog'),
        ),
    ]
